title: Gravstrap theme
author:
  name: Joe Bloggs
  email: 'joe@test.com'
metadata:
    description: Gravstrap Theme helps you to start a new Grav CMS site with Bootstrap support and several ready to use modules. It is also perfect to start a new Bootstrap custom theme, to create your unique design'

credits: This website is made with <a href="http://getgrav.org/">Grav CMS</a> and it is powerd by <a href="http://diblas.net/themes/gravstrap-theme-to-start-grav-cms-site-with-bootstrap-support/">Gravstrap Theme</a> and <a href="http://diblas.net/plugins/use-bootstrap-elements-in-the-grav-cms-way/">Gravstrap Plugin</a>.
copyright: Joe Bloggs
